In [1]:
import numpy as np

In [2]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[25, 0, 6], [1, 0, 6]])
X

array([[25,  0,  6],
       [ 1,  0,  6]])

In [3]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [9]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([25,  1])

In [7]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([1, 0, 6])

2. ulangi soal nomor 1 menggunakan Pytorch

In [8]:
import torch

In [16]:
X_pt = torch.tensor([[25, 0, 6], [1, 0, 6]])
X_pt

tensor([[25,  0,  6],
        [ 1,  0,  6]])

In [17]:
X_pt.shape

torch.Size([2, 3])

In [18]:
X_pt[:,0]

tensor([25,  1])

In [19]:
X_pt[1,:]

tensor([1, 0, 6])

3. ulangi soal nomor 1 menggunakan Tensorflow

In [20]:
import tensorflow as tf

In [21]:
X_tf = tf.Variable([[25, 0, 6], [1, 0, 6]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25,  0,  6],
       [ 1,  0,  6]], dtype=int32)>

In [22]:
X_tf.shape

TensorShape([2, 3])

In [25]:
X_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([25,  1], dtype=int32)>

In [26]:
X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 0, 6], dtype=int32)>